[package]
name = "replay"
version = "0.1.0"
authors = ["Acasune <tttt4aaaa@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.3"
proconio = "0.3.6"

##############

[[bin]]
name = "abc245-d"
path = "abc245d.rs"

[[bin]]
name = "abc245-e"
path = "abc245e.rs"
