[package]
name = "abc170"
version = "0.1.0"
authors = ["Acasune <tttt4aaaa@gmail.com>"]
edition = "2018"

##############
##  abc170  ##
##############


[[bin]]
name = "abc170-a"
path = "abc170/a.rs"

[[bin]]
name = "abc170-b"
path = "abc170/b.rs"

[[bin]]
name = "abc170-c"
path = "abc170/c.rs"

[[bin]]
name = "abc170-d"
path = "abc170/d.rs"


##############
##  abc171  ##
##############

[[bin]]
name = "abc171-a"
path = "abc171/a.rs"

[[bin]]
name = "abc171-b"
path = "abc171/b.rs"

[[bin]]
name = "abc171-c"
path = "abc171/c.rs"

[[bin]]
name = "abc171-d"
path = "abc171/d.rs"


##############
##  abc172  ##
##############

[[bin]]
name = "abc172-a"
path = "abc172/a.rs"

[[bin]]
name = "abc172-b"
path = "abc172/b.rs"

[[bin]]
name = "abc172-c"
path = "abc172/c.rs"

[[bin]]
name = "abc172-d"
path = "abc172/d.rs"
