[package]
name = "abc170"
version = "0.1.0"
authors = ["Acasune <tttt4aaaa@gmail.com>"]
edition = "2018"


########################
##  05_binary-search  ##
########################

[[bin]]
name = "08-ALDS1-4-B"
path = "selections-for-intermediate-contestants/05-binary-search/08-ALDS1-4-B.rs"

[[bin]]
name = "09-joi2009ho_b"
path = "selections-for-intermediate-contestants/05-binary-search/09-joi2009ho_b.rs"

[[bin]]
name = "10-abc007"
path = "selections-for-intermediate-contestants/05-binary-search/10-abc007.rs"

[[bin]]
name = "11-abc023-d"
path = "selections-for-intermediate-contestants/05-binary-search/11-abc023-d.rs"

[[bin]]
name = "12-arc054_b"
path = "selections-for-intermediate-contestants/05-binary-search/12-arc054_b.rs"
