[package]
name = "abc170"
version = "0.1.0"
authors = ["Acasune <tttt4aaaa@gmail.com>"]
edition = "2018"


########################
##  05_binary-search  ##
########################

[[bin]]
name = "18-ALDS1-4-B"
path = "selections-for-intermediate-contestants/05-binary-search/18-ALDS1-4-B.rs"

[[bin]]
name = "19-joi2009ho_b"
path = "selections-for-intermediate-contestants/05-binary-search/19-joi2009ho_b.rs"

[[bin]]
name = "20-abc007"
path = "selections-for-intermediate-contestants/05-binary-search/20-abc077-c.rs"

[[bin]]
name = "21-abc023-d"
path = "selections-for-intermediate-contestants/05-binary-search/21-abc023-d.rs"

[[bin]]
name = "22-arc054_b"
path = "selections-for-intermediate-contestants/05-binary-search/22-arc054_b.rs"

[[bin]]
name = "23-joi2008ho_c"
path = "selections-for-intermediate-contestants/05-binary-search/23-joi2008ho_c.rs"


##############################
##  08_dp-knapsack-problem  ##
##############################

[[bin]]
name = "34-ALDS1-10-A"
path = "selections-for-intermediate-contestants/08-dp-knapsack-problem/34-ALDS1-10-A.rs"
